//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoomInfo
    {
        public int room_id { get; set; }
        public string room_name { get; set; }
        public string room_type { get; set; }
        public Nullable<double> room_price { get; set; }
    }
}
