//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BookingInfo
    {
        public int booking_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public string room_type { get; set; }
        public Nullable<System.DateTime> from_dt { get; set; }
        public Nullable<System.DateTime> to_dt { get; set; }
        public string cust_name { get; set; }
        public Nullable<double> total_amt { get; set; }
        public string transactn_type { get; set; }
    }
}
